"""foundation

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("modality", sa.String(length=40), nullable=False),
        sa.Column("crest_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("plan", sa.String(length=16), server_default="free", nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("president_membership_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code ~ '^[A-Z0-9]{6,10}$'", name=op.f("ck_teams_code")),
        sa.CheckConstraint("plan IN ('free', 'pro')", name=op.f("ck_teams_plan")),
        sa.CheckConstraint("state ~ '^[A-Z]{2}$'", name=op.f("ck_teams_state")),
        sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f("ck_teams_status")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_teams_name")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phone IS NULL OR phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_users_phone_e164")
        ),
        sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f("ck_users_status")),
        sa.CheckConstraint(
            "email IS NOT NULL OR phone IS NOT NULL", name=op.f("ck_users_contact_required")
        ),
        sa.CheckConstraint(
            "email IS NULL OR email = lower(email)", name=op.f("ck_users_email_normalized")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_table(
        "players",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(display_name)) > 0", name=op.f("ck_players_name")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_players_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("user_id", name=op.f("uq_players_user_id")),
    )
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="member", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('member', 'admin')", name=op.f("ck_team_memberships_role")),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name=op.f("ck_team_memberships_status")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_team_memberships_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_memberships_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_memberships")),
        sa.UniqueConstraint("team_id", "id", name="uq_membership_team_id"),
        sa.UniqueConstraint("team_id", "player_id", name="uq_membership_team_player"),
    )
    op.create_index(
        "ix_memberships_team_status", "team_memberships", ["team_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_team_memberships_player_id"), "team_memberships", ["player_id"], unique=False
    )
    op.create_table(
        "membership_permissions",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "permission IN ('manage_team', 'manage_members')",
            name=op.f("ck_membership_permissions_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["team_memberships.id"],
            name=op.f("fk_membership_permissions_membership_id_team_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_permissions")),
        sa.UniqueConstraint(
            "membership_id", "permission", name=op.f("uq_membership_permissions_membership_id")
        ),
    )
    op.create_index(
        op.f("ix_membership_permissions_membership_id"),
        "membership_permissions",
        ["membership_id"],
        unique=False,
    )
    # Create the circular reference only after both tables exist.
    op.create_foreign_key(
        "fk_team_president_membership",
        "teams",
        "team_memberships",
        ["id", "president_membership_id"],
        ["team_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    op.drop_constraint("fk_team_president_membership", "teams", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_membership_permissions_membership_id"), table_name="membership_permissions"
    )
    op.drop_table("membership_permissions")
    op.drop_index(op.f("ix_team_memberships_player_id"), table_name="team_memberships")
    op.drop_index("ix_memberships_team_status", table_name="team_memberships")
    op.drop_table("team_memberships")
    op.drop_table("players")
    op.drop_table("users")
    op.drop_table("teams")
    # ### end Alembic commands ###
