"""launch_essentials

Revision ID: 0013
Revises: 0012
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_recoveries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("handle_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 5", name=op.f("ck_password_recoveries_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_recoveries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_recoveries")),
        sa.UniqueConstraint("handle_hash", name=op.f("uq_password_recoveries_handle_hash")),
        sa.UniqueConstraint("user_id", name=op.f("uq_password_recoveries_user_id")),
    )
    op.create_table(
        "team_audit",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_team_audit_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_audit_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_audit")),
    )
    op.create_index(op.f("ix_team_audit_team_id"), "team_audit", ["team_id"], unique=False)
    op.create_table(
        "lineups",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("modality", sa.String(length=40), nullable=False),
        sa.Column("formation", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("creation_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "modality IN ('campo', 'society', 'futsal')", name=op.f("ck_lineups_modality")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_lineups_version")),
        sa.ForeignKeyConstraint(
            ["team_id", "event_id"],
            ["events.team_id", "events.id"],
            name=op.f("fk_lineups_team_id_events"),
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_lineups_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineups")),
        sa.UniqueConstraint("team_id", "command_id", name="uq_lineups_command"),
        sa.UniqueConstraint("team_id", "id", name=op.f("uq_lineups_team_id")),
    )
    op.create_index(op.f("ix_lineups_team_id"), "lineups", ["team_id"], unique=False)
    op.create_table(
        "lineup_positions",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("lineup_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("slot >= 0 AND slot < 11", name=op.f("ck_lineup_positions_slot")),
        sa.ForeignKeyConstraint(
            ["team_id", "lineup_id"],
            ["lineups.team_id", "lineups.id"],
            name=op.f("fk_lineup_positions_team_id_lineups"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id", "membership_id"],
            ["team_memberships.team_id", "team_memberships.id"],
            name=op.f("fk_lineup_positions_team_id_team_memberships"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineup_positions")),
        sa.UniqueConstraint("lineup_id", "membership_id", name="uq_lineup_member"),
        sa.UniqueConstraint("lineup_id", "slot", name="uq_lineup_slot"),
    )
    op.add_column(
        "team_memberships",
        sa.Column(
            "positions",
            postgresql.ARRAY(sa.String(length=4)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "team_memberships", sa.Column("primary_position", sa.String(length=4), nullable=True)
    )
    op.add_column(
        "team_memberships",
        sa.Column("roster_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column("teams", sa.Column("category", sa.String(length=16), nullable=True))
    op.drop_constraint(op.f("ck_team_memberships_status"), "team_memberships", type_="check")
    op.create_check_constraint(
        op.f("ck_team_memberships_status"),
        "team_memberships",
        "status IN ('active', 'inactive', 'removed')",
    )
    op.create_check_constraint(
        op.f("ck_team_memberships_roster_version"), "team_memberships", "roster_version > 0"
    )
    op.create_check_constraint(
        op.f("ck_team_memberships_primary_position"),
        "team_memberships",
        "(cardinality(positions) = 0 AND primary_position IS NULL) OR "
        "(cardinality(positions) > 0 AND primary_position IS NOT NULL "
        "AND primary_position = ANY(positions))",
    )
    op.create_check_constraint(
        op.f("ck_teams_category"),
        "teams",
        "category IS NULL OR category IN ('male', 'female', 'mixed')",
    )


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM team_audit) OR EXISTS (SELECT 1 FROM lineups) "
            "OR EXISTS (SELECT 1 FROM password_recoveries) "
            "OR EXISTS (SELECT 1 FROM teams WHERE category IS NOT NULL) "
            "OR EXISTS (SELECT 1 FROM team_memberships "
            "WHERE status = 'removed' OR cardinality(positions) > 0)"
        )
    ):
        raise RuntimeError("Downgrade bloqueado: preserve os dados do lançamento e a auditoria.")
    op.drop_constraint(op.f("ck_teams_category"), "teams", type_="check")
    op.drop_constraint(
        op.f("ck_team_memberships_primary_position"), "team_memberships", type_="check"
    )
    op.drop_constraint(
        op.f("ck_team_memberships_roster_version"), "team_memberships", type_="check"
    )
    op.drop_constraint(op.f("ck_team_memberships_status"), "team_memberships", type_="check")
    op.create_check_constraint(
        op.f("ck_team_memberships_status"), "team_memberships", "status IN ('active', 'inactive')"
    )
    op.drop_column("teams", "category")
    op.drop_column("team_memberships", "roster_version")
    op.drop_column("team_memberships", "primary_position")
    op.drop_column("team_memberships", "positions")
    op.drop_table("lineup_positions")
    op.drop_index(op.f("ix_lineups_team_id"), table_name="lineups")
    op.drop_table("lineups")
    op.drop_index(op.f("ix_team_audit_team_id"), table_name="team_audit")
    op.drop_table("team_audit")
    op.drop_table("password_recoveries")
    # ### end Alembic commands ###
