"""billing_asaas

Revision ID: 0014
Revises: 0013
"""

import sqlalchemy as sa
from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_webhooks",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_webhooks")),
        sa.UniqueConstraint("event_id", name=op.f("uq_billing_webhooks_event_id")),
    )
    op.create_table(
        "billing_audit",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_billing_audit_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_billing_audit_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_audit")),
    )
    op.create_index(op.f("ix_billing_audit_team_id"), "billing_audit", ["team_id"], unique=False)
    op.create_table(
        "billing_subscriptions",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("plan_code", sa.String(length=40), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=True),
        sa.Column("checkout_id", sa.String(length=100), nullable=True),
        sa.Column("operation_status", sa.String(length=24), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('PIX', 'CREDIT_CARD')", name=op.f("ck_billing_subscriptions_method")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_billing_subscriptions_amount")),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_billing_subscriptions_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_subscriptions")),
        sa.UniqueConstraint("checkout_id", name=op.f("uq_billing_subscriptions_checkout_id")),
        sa.UniqueConstraint("provider_id", name=op.f("uq_billing_subscriptions_provider_id")),
        sa.UniqueConstraint("team_id", "command_id", name="uq_billing_subscriptions_command"),
    )
    op.create_index(
        op.f("ix_billing_subscriptions_team_id"), "billing_subscriptions", ["team_id"], unique=False
    )
    op.create_table(
        "team_billing",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("plan_code", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=True),
        sa.Column("customer_attempted", sa.Boolean(), nullable=False),
        sa.Column("grant_active", sa.Boolean(), nullable=False),
        sa.Column("grant_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('sandbox', 'production')", name=op.f("ck_team_billing_environment")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_billing_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_billing")),
        sa.UniqueConstraint("customer_id", name=op.f("uq_team_billing_customer_id")),
        sa.UniqueConstraint("team_id", name=op.f("uq_team_billing_team_id")),
    )
    op.create_table(
        "billing_payments",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["billing_subscriptions.id"],
            name=op.f("fk_billing_payments_subscription_id_billing_subscriptions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_payments")),
        sa.UniqueConstraint("provider_id", name=op.f("uq_billing_payments_provider_id")),
    )
    op.create_index(
        op.f("ix_billing_payments_subscription_id"),
        "billing_payments",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    for table in (
        "billing_payments",
        "billing_subscriptions",
        "billing_audit",
        "billing_webhooks",
        "team_billing",
    ):
        if connection.execute(sa.text(f'SELECT EXISTS (SELECT 1 FROM "{table}")')).scalar():
            raise RuntimeError("Downgrade blocked: preserve commercial billing history")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_billing_payments_subscription_id"), table_name="billing_payments")
    op.drop_table("billing_payments")
    op.drop_table("team_billing")
    op.drop_index(op.f("ix_billing_subscriptions_team_id"), table_name="billing_subscriptions")
    op.drop_table("billing_subscriptions")
    op.drop_index(op.f("ix_billing_audit_team_id"), table_name="billing_audit")
    op.drop_table("billing_audit")
    op.drop_table("billing_webhooks")
    # ### end Alembic commands ###
