"""Persistent messages for one account; independent from UI and delivery channels."""

from enum import StrEnum


class NotificationType(StrEnum):
    TEAM_JOIN_REQUEST = "TEAM_JOIN_REQUEST"
    TEAM_JOIN_APPROVED = "TEAM_JOIN_APPROVED"
    TEAM_JOIN_REJECTED = "TEAM_JOIN_REJECTED"
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_CANCELLED = "EVENT_CANCELLED"
    ATTENDANCE_REMINDER = "ATTENDANCE_REMINDER"
    FINANCE_CHARGE_CREATED = "FINANCE_CHARGE_CREATED"
    FINANCE_PAYMENT_REGISTERED = "FINANCE_PAYMENT_REGISTERED"
    FINANCE_PAYMENT_REVERSED = "FINANCE_PAYMENT_REVERSED"


class NotificationAction(StrEnum):
    OPEN_TEAM = "OPEN_TEAM"
    OPEN_JOIN_REQUESTS = "OPEN_JOIN_REQUESTS"
    OPEN_EVENT = "OPEN_EVENT"
    OPEN_FINANCE_CHARGE = "OPEN_FINANCE_CHARGE"
